### ISSUE TITLE
`aes128ctrbs` gives incorrect results

### ISSUE THREAD

**Issue by hugovincent** [Ko-/aes-armcortexm#1]
The bitsliced variant seems to give a different (incorrect) result, compared to the non-bitsliced version (`aes128ctr`), which gives the correct result (I have checked with some of the NIST 800-38A published test vectors).

**Comment by Ko-** [comment]
Thanks for reporting. I'll look into it, but I'm not in my office until Monday.

**Comment by Ko-** [comment]
You were right. There appeared to be bug that was introduced at a very late stage. Commit 45103cb fixes this and should at least give you a correct first block. Once again thanks for reporting.

I also noticed that all my CTR mode implementations deviate from the SP800-38A test vectors from the second block onwards, due to a different choice of order of the nonce and the counter. I based the counter-mode caching in the `aes128ctr` implementation on Hongjun Wu's eSTREAM implementation, where also the first 32 bits are used as counter, instead of the last 32 bits. In `aes128ctrbs` a workaround would be to change `add r8, #1` to `rev r11, r11; add r11, #1; rev r11, r11`. For `aes128ctr`, a fix is slightly tricker due to this caching. Ideally, the nonce and counter should just be rearranged to match the SP800-38A test vectors.

**Comment by hugovincent** [comment]
Thanks @Ko-!

I noticed about the nonce/counter ordering and endianness too, but presumed you'd made that choice for efficiency (saving a few cycles flipping the endianness). It was fine for my application.  I used the following Python/PyCrypto fragment for generating some vectors compatible with your ordering:
```python
key, nonce = "\xB1\x4A...", "..." # byte strings
ctr = Counter.new(32, suffix=nonce, little_endian=True, initial_value=0)
aes = AES.new(key, mode=AES.MODE_CTR, counter=ctr)
ciphertext = aes.encrypt(plaintext)
```
